package com.ibkr.entity;

import java.io.Serializable;
import java.util.Date;

public class StockProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.id
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.cts
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private Date cts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.symbol
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.sec_type
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private String secType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.unit
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.name
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.exchange
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private String exchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.market
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private String market;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.time_zone
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private String timeZone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.start_time
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.end_time
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.before_time
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private Date beforeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.after_time
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private Date afterTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.pre_close
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private String preClose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.pre_start
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private String preStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.high_price
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private String highPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.low_price
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private String lowPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.change
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private String change;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.float_shares
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private Long floatShares;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.shares
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private Long shares;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.market_value
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private Long marketValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.shortable
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private Integer shortable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_product.status
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_product
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.id
     *
     * @return the value of stock_product.id
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.id
     *
     * @param id the value for stock_product.id
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.cts
     *
     * @return the value of stock_product.cts
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public Date getCts() {
        return cts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.cts
     *
     * @param cts the value for stock_product.cts
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setCts(Date cts) {
        this.cts = cts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.symbol
     *
     * @return the value of stock_product.symbol
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.symbol
     *
     * @param symbol the value for stock_product.symbol
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.sec_type
     *
     * @return the value of stock_product.sec_type
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public String getSecType() {
        return secType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.sec_type
     *
     * @param secType the value for stock_product.sec_type
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setSecType(String secType) {
        this.secType = secType == null ? null : secType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.unit
     *
     * @return the value of stock_product.unit
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.unit
     *
     * @param unit the value for stock_product.unit
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.name
     *
     * @return the value of stock_product.name
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.name
     *
     * @param name the value for stock_product.name
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.exchange
     *
     * @return the value of stock_product.exchange
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.exchange
     *
     * @param exchange the value for stock_product.exchange
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.market
     *
     * @return the value of stock_product.market
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.market
     *
     * @param market the value for stock_product.market
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setMarket(String market) {
        this.market = market == null ? null : market.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.time_zone
     *
     * @return the value of stock_product.time_zone
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public String getTimeZone() {
        return timeZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.time_zone
     *
     * @param timeZone the value for stock_product.time_zone
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setTimeZone(String timeZone) {
        this.timeZone = timeZone == null ? null : timeZone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.start_time
     *
     * @return the value of stock_product.start_time
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.start_time
     *
     * @param startTime the value for stock_product.start_time
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.end_time
     *
     * @return the value of stock_product.end_time
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.end_time
     *
     * @param endTime the value for stock_product.end_time
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.before_time
     *
     * @return the value of stock_product.before_time
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public Date getBeforeTime() {
        return beforeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.before_time
     *
     * @param beforeTime the value for stock_product.before_time
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setBeforeTime(Date beforeTime) {
        this.beforeTime = beforeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.after_time
     *
     * @return the value of stock_product.after_time
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public Date getAfterTime() {
        return afterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.after_time
     *
     * @param afterTime the value for stock_product.after_time
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setAfterTime(Date afterTime) {
        this.afterTime = afterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.pre_close
     *
     * @return the value of stock_product.pre_close
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public String getPreClose() {
        return preClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.pre_close
     *
     * @param preClose the value for stock_product.pre_close
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setPreClose(String preClose) {
        this.preClose = preClose == null ? null : preClose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.pre_start
     *
     * @return the value of stock_product.pre_start
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public String getPreStart() {
        return preStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.pre_start
     *
     * @param preStart the value for stock_product.pre_start
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setPreStart(String preStart) {
        this.preStart = preStart == null ? null : preStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.high_price
     *
     * @return the value of stock_product.high_price
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public String getHighPrice() {
        return highPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.high_price
     *
     * @param highPrice the value for stock_product.high_price
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setHighPrice(String highPrice) {
        this.highPrice = highPrice == null ? null : highPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.low_price
     *
     * @return the value of stock_product.low_price
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public String getLowPrice() {
        return lowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.low_price
     *
     * @param lowPrice the value for stock_product.low_price
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setLowPrice(String lowPrice) {
        this.lowPrice = lowPrice == null ? null : lowPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.change
     *
     * @return the value of stock_product.change
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public String getChange() {
        return change;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.change
     *
     * @param change the value for stock_product.change
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setChange(String change) {
        this.change = change == null ? null : change.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.float_shares
     *
     * @return the value of stock_product.float_shares
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public Long getFloatShares() {
        return floatShares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.float_shares
     *
     * @param floatShares the value for stock_product.float_shares
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setFloatShares(Long floatShares) {
        this.floatShares = floatShares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.shares
     *
     * @return the value of stock_product.shares
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public Long getShares() {
        return shares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.shares
     *
     * @param shares the value for stock_product.shares
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setShares(Long shares) {
        this.shares = shares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.market_value
     *
     * @return the value of stock_product.market_value
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public Long getMarketValue() {
        return marketValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.market_value
     *
     * @param marketValue the value for stock_product.market_value
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setMarketValue(Long marketValue) {
        this.marketValue = marketValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.shortable
     *
     * @return the value of stock_product.shortable
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public Integer getShortable() {
        return shortable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.shortable
     *
     * @param shortable the value for stock_product.shortable
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setShortable(Integer shortable) {
        this.shortable = shortable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_product.status
     *
     * @return the value of stock_product.status
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_product.status
     *
     * @param status the value for stock_product.status
     *
     * @mbg.generated Fri Nov 23 10:54:54 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}