package com.ibkr.entity;

import java.io.Serializable;
import java.util.Date;

public class StockOptions implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_options.id
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_options.cts
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    private Date cts;

    private Date uts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_options.price
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_options.symbol
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_options.strike
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    private String strike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_options.right
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    private String right;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_options.expiry
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    private String expiry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_options.volume
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    private Integer volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_options
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_options.id
     *
     * @return the value of stock_options.id
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_options.id
     *
     * @param id the value for stock_options.id
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_options.cts
     *
     * @return the value of stock_options.cts
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public Date getCts() {
        return cts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_options.cts
     *
     * @param cts the value for stock_options.cts
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public void setCts(Date cts) {
        this.cts = cts;
    }


    public Date getUts() {
        return uts;
    }

    public void setUts(Date uts) {
        this.uts = uts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_options.price
     *
     * @return the value of stock_options.price
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_options.price
     *
     * @param price the value for stock_options.price
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_options.symbol
     *
     * @return the value of stock_options.symbol
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_options.symbol
     *
     * @param symbol the value for stock_options.symbol
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_options.strike
     *
     * @return the value of stock_options.strike
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public String getStrike() {
        return strike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_options.strike
     *
     * @param strike the value for stock_options.strike
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public void setStrike(String strike) {
        this.strike = strike == null ? null : strike.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_options.right
     *
     * @return the value of stock_options.right
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public String getRight() {
        return right;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_options.right
     *
     * @param right the value for stock_options.right
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public void setRight(String right) {
        this.right = right == null ? null : right.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_options.expiry
     *
     * @return the value of stock_options.expiry
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public String getExpiry() {
        return expiry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_options.expiry
     *
     * @param expiry the value for stock_options.expiry
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public void setExpiry(String expiry) {
        this.expiry = expiry == null ? null : expiry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_options.volume
     *
     * @return the value of stock_options.volume
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public Integer getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_options.volume
     *
     * @param volume the value for stock_options.volume
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    public void setVolume(Integer volume) {
        this.volume = volume;
    }
}