package com.ibkr.mapper;

import com.ibkr.entity.StockProduct;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface StockProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_product
     *
     * @mbg.generated Tue Nov 06 14:16:15 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_product
     *
     * @mbg.generated Tue Nov 06 14:16:15 CST 2018
     */
    int insert(StockProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_product
     *
     * @mbg.generated Tue Nov 06 14:16:15 CST 2018
     */
    int insertSelective(StockProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_product
     *
     * @mbg.generated Tue Nov 06 14:16:15 CST 2018
     */
    StockProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_product
     *
     * @mbg.generated Tue Nov 06 14:16:15 CST 2018
     */
    int updateByPrimaryKeySelective(List<StockProduct> stockProducts);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_product
     *
     * @mbg.generated Tue Nov 06 14:16:15 CST 2018
     */
    int updateByPrimaryKey(StockProduct record);

    List<StockProduct> selectAll(Map<String, Object> params);


    StockProduct selectBySymbol(String symbol);

    List<StockProduct> selectFocusProduct(Map<String,Object> params);
}