package com.ibkr.mapper;

import com.ibkr.entity.StockOptions;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StockOptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_options
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_options
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    int insert(StockOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_options
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    StockOptions selectByPrimaryKey(StockOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_options
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    int updateByPrimaryKeySelective(StockOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_options
     *
     * @mbg.generated Sat Feb 23 15:30:54 CST 2019
     */
    int updateByPrimaryKey(StockOptions record);

    /**
     *
     * @param stockOptions
     * @return
     */
    List<StockOptions> selectByOptions(StockOptions stockOptions);
}